"""empty message

Revision ID: c076e0b66b4b
Revises: 339b0a102ce6
Create Date: 2024-04-25 19:29:17.075739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c076e0b66b4b'
down_revision = '339b0a102ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('climate', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('planetDesc', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('population', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('surface_water', sa.String(length=20), nullable=False))
        batch_op.drop_constraint('planets_whatever_key', type_='unique')
        batch_op.drop_column('lol')
        batch_op.drop_column('whatever')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=25), nullable=False))
        batch_op.create_unique_constraint(None, ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_name')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('whatever', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lol', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('planets_whatever_key', ['whatever'])
        batch_op.drop_column('surface_water')
        batch_op.drop_column('terrain')
        batch_op.drop_column('population')
        batch_op.drop_column('gravity')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('planetDesc')
        batch_op.drop_column('diameter')
        batch_op.drop_column('climate')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
